import 'package:flutter/material.dart';

final List<DropdownMenuEntry<String?>> states = [
    const DropdownMenuEntry(
      value: null,
      label: 'Select State',
    ),
    const DropdownMenuEntry(value: 'AL', label: 'AL'),
    const DropdownMenuEntry(value: 'AK', label: 'AK'),
    const DropdownMenuEntry(value: 'AZ', label: 'AZ'),
    const DropdownMenuEntry(value: 'AR', label: 'AR'),
    const DropdownMenuEntry(value: 'CA', label: 'CA'),
    const DropdownMenuEntry(value: 'CO', label: 'CO'),
    const DropdownMenuEntry(value: 'CT', label: 'CT'),
    const DropdownMenuEntry(value: 'DE', label: 'DE'),
    const DropdownMenuEntry(value: 'FL', label: 'FL'),
    const DropdownMenuEntry(value: 'GA', label: 'GA'),
    const DropdownMenuEntry(value: 'HI', label: 'HI'),
    const DropdownMenuEntry(value: 'ID', label: 'ID'),
    const DropdownMenuEntry(value: 'IL', label: 'IL'),
    const DropdownMenuEntry(value: 'IN', label: 'IN'),
    const DropdownMenuEntry(value: 'IA', label: 'IA'),
    const DropdownMenuEntry(value: 'KS', label: 'KS'),
    const DropdownMenuEntry(value: 'KY', label: 'KY'),
    const DropdownMenuEntry(value: 'LA', label: 'LA'),
    const DropdownMenuEntry(value: 'ME', label: 'ME'),
    const DropdownMenuEntry(value: 'MD', label: 'MD'),
    const DropdownMenuEntry(value: 'MA', label: 'MA'),
    const DropdownMenuEntry(value: 'MI', label: 'MI'),
    const DropdownMenuEntry(value: 'MN', label: 'MN'),
    const DropdownMenuEntry(value: 'MS', label: 'MS'),
    const DropdownMenuEntry(value: 'MO', label: 'MO'),
    const DropdownMenuEntry(value: 'MT', label: 'MT'),
    const DropdownMenuEntry(value: 'NE', label: 'NE'),
    const DropdownMenuEntry(value: 'NV', label: 'NV'),
    const DropdownMenuEntry(value: 'NH', label: 'NH'),
    const DropdownMenuEntry(value: 'NJ', label: 'NJ'),
    const DropdownMenuEntry(value: 'NM', label: 'NM'),
    const DropdownMenuEntry(value: 'NY', label: 'NY'),
    const DropdownMenuEntry(value: 'NC', label: 'NC'),
    const DropdownMenuEntry(value: 'ND', label: 'ND'),
    const DropdownMenuEntry(value: 'OH', label: 'OH'),
    const DropdownMenuEntry(value: 'OK', label: 'OK'),
    const DropdownMenuEntry(value: 'OR', label: 'OR'),
    const DropdownMenuEntry(value: 'PA', label: 'PA'),
    const DropdownMenuEntry(value: 'RI', label: 'RI'),
    const DropdownMenuEntry(value: 'SC', label: 'SC'),
    const DropdownMenuEntry(value: 'SD', label: 'SD'),
    const DropdownMenuEntry(value: 'TN', label: 'TN'),
    const DropdownMenuEntry(value: 'TX', label: 'TX'),
    const DropdownMenuEntry(value: 'UT', label: 'UT'),
    const DropdownMenuEntry(value: 'VT', label: 'VT'),
    const DropdownMenuEntry(value: 'VA', label: 'VA'),
    const DropdownMenuEntry(value: 'WA', label: 'WA'),
    const DropdownMenuEntry(value: 'WV', label: 'WV'),
    const DropdownMenuEntry(value: 'WI', label: 'WI'),
    const DropdownMenuEntry(value: 'WY', label: 'WY'),
  ];